gpu_id: '0'
log_wandb: False

# SS4Rec settings
hidden_size: 64                 # (int) Number of features in the hidden state. 
num_layers: 2                   # (int) Number of layers.
dropout_prob: 0.2               # (float) Dropout rate.
loss_type: 'CE'                 # (str) Type of loss function. Range in ['BPR', 'CE'].

# S6
d_state: 32                     # (int) SSM state expansion factor
d_conv: 4                       # (int) Local convolution width
expand: 2                       # (int) Block expansion factor
# S5
dt_min: 0.001
dt_max: 0.1
d_H: 64 # == hidden_size
d_P: 32


# dataset settings
# dataset: ml-1m
# dataset: amazon-sports
dataset: amazon-video-games
# dataset: kuairec_big
# dataset: kuairec_small
MAX_ITEM_LIST_LENGTH: 50  
MIN_ITEM_LIST_LENGTH: 0 


USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIMESTAMP_FIELD: timestamp
load_col:
    inter: [user_id, item_id, timestamp]

user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

# training settings
# https://www.recbole.io/hyperparameters/index.html
epochs: 200
train_batch_size: 1024
learner: adam
learning_rate: 0.001 # for ss
eval_step: 1
stopping_step: 10
train_neg_sample_args: ~

# evalution settings
metrics: ['Hit', 'NDCG', 'MRR']
valid_metric: NDCG@10
eval_batch_size: 2048
weight_decay: 0.0
topk: [10]
next_n: 1